### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by sonnykt** [govCMS/GovCMS7#259]
Hello,

For some reasons `phing` keeps failing when I'm trying to install it on my local environment. The same error occurs for releases from `7.x-2.x`, `release/7.x-2.1`, `release/7.x-2.0`, etc. to `7.x-2.0-beta10` (commit `30cec9f`).

```
    [drush]  * [@self.3] Project xmlsitemap contains 9 modules: xmlsitemap_user, xmlsitemap_taxonomy, xmlsitemap_node, xmlsitemap_modal, xmlsitemap_menu, xmlsitemap_i18n, xmlsitemap_engines, xmlsitemap_custom, xmlsitemap.
    [drush]  * [@self.5] sh: line 1: 78737 Trace/BPT trap: 5       svn info /private/tmp/make_tmp_1464587350_574bd456a5ab2/__build__/profiles/govcms/modules/contrib 2>&1
    [drush]  * [@self.4] sh: line 1: 78799 Trace/BPT trap: 5       svn info /private/tmp/make_tmp_1464587350_574bd456a5ab2/__build__/profiles/govcms/themes/contrib 2>&1
    [drush]  * [@self.2] sh: line 1: 78843 Trace/BPT trap: 5       wget --version 2>&1
    [drush]  * [@self.2] sh: line 1: 78847 Trace/BPT trap: 5       curl --version 2>&1
    [drush]  * [@self.0] sh: line 1: 78863 Trace/BPT trap: 5       wget --version 2>&1
    [drush]  * [@self.0] sh: line 1: 78865 Trace/BPT trap: 5       curl --version 2>&1
    [drush]  * [@self.2] sh: line 1: 78857 Trace/BPT trap: 5       svn info /private/tmp/make_tmp_1464587350_574bd456a5ab2/__build__/profiles/govcms/modules/contrib 2>&1
    [drush]  * [@self.5] sh: line 1: 78880 Trace/BPT trap: 5       wget --version 2>&1
    [drush]  * [@self.5] sh: line 1: 78886 Trace/BPT trap: 5       curl --version 2>&1
    [drush]  * [@self.0] sh: line 1: 78883 Trace/BPT trap: 5       svn info /private/tmp/make_tmp_1464587350_574bd456a5ab2/__build__/profiles/govcms/modules/contrib 2>&1
    [drush]  * [@self.0] Project views_bulk_operations contains 2 modules: actions_permissions, views_bulk_operations.
    [drush]  * [@self.5] sh: line 1: 78898 Trace/BPT trap: 5       svn info /private/tmp/make_tmp_1464587350_574bd456a5ab2/__build__/profiles/govcms/modules/contrib 2>&1
    [drush]  * [@self.0] sh: line 1: 78916 Trace/BPT trap: 5       wget --version 2>&1
    [drush]  * [@self.0] sh: line 1: 78918 Trace/BPT trap: 5       curl --version 2>&1
    [drush]  * [@self.0] sh: line 1: 78929 Trace/BPT trap: 5       svn info /private/tmp/make_tmp_1464587350_574bd456a5ab2/__build__/profiles/govcms/modules/contrib 2>&1
    [drush]  * [@self.5] sh: line 1: 78934 Trace/BPT trap: 5       wget --version 2>&1
    [drush]  * [@self.5] sh: line 1: 78938 Trace/BPT trap: 5       curl --version 2>&1
    [drush]  * [@self.5] sh: line 1: 78946 Trace/BPT trap: 5       svn info /private/tmp/make_tmp_1464587350_574bd456a5ab2/__build__/profiles/govcms/themes/contrib 2>&1
Execution of target "make:local" failed for the following reason: build/phing/build.xml:305:38: Drush exited with code 1
[phingcall] build/phing/build.xml:305:38: Drush exited with code 1
       [if] Error in IfTask
Execution of target "make" failed for the following reason: build/phing/build.xml:240:12: Error in IfTask
#0 build/vendor/phing/phing/classes/phing/UnknownElement.php(96): TaskAdapter->main()
#1 build/vendor/phing/phing/classes/phing/Task.php(260): UnknownElement->main()
#2 build/vendor/phing/phing/classes/phing/Target.php(297): Task->perform()
#3 build/vendor/phing/phing/classes/phing/Target.php(320): Target->main()
#4 build/vendor/phing/phing/classes/phing/Project.php(824): Target->performTasks()
#5 build/vendor/phing/phing/classes/phing/Project.php(797): Project->executeTarget('build')
#6 build/vendor/phing/phing/classes/phing/Phing.php(590): Project->executeTargets(Array)
#7 build/vendor/phing/phing/classes/phing/Phing.php(170): Phing->runBuild()
#8 build/vendor/phing/phing/classes/phing/Phing.php(278): Phing::start(Array, NULL)
#9 build/vendor/phing/phing/bin/phing.php(43): Phing::fire(Array)
#10 build/vendor/phing/phing/bin/phing(20): require_once('/Volumes/Data/w...')
#11 {main}
```

I could only install govCMS from commit `d6c33da` (7.x-2.0-beta9) backward.

```
    [drush]  * [@self.0] sh: line 1: 82082 Trace/BPT trap: 5       wget --version 2>&1
    [drush]  * [@self.0] sh: line 1: 82086 Trace/BPT trap: 5       curl --version 2>&1
    [drush]  * [@self.0] sh: line 1: 82094 Trace/BPT trap: 5       svn info /private/tmp/make_tmp_1464587411_574bd493dabfa/__build__/profiles/govcms/modules/contrib 2>&1
    [drush]  * [@self.0] Project xmlsitemap contains 9 modules: xmlsitemap_user, xmlsitemap_taxonomy, xmlsitemap_node, xmlsitemap_modal, xmlsitemap_menu, xmlsitemap_i18n, xmlsitemap_engines, xmlsitemap_custom, xmlsitemap.
[phingcall] Calling Buildfile 'build/phing/build.xml' with target 'rm-robotstxt'
     [exec] 
     [exec] HEAD
 [property] Loading build/phing/build.properties

govcms > rm-robotstxt:
```

I'm running OSX 10.11.5, PHP 5.6.15, Drush 8.0.1.

**Comment by sonnykt** [comment]
Update: it still fails with Drush 8.1.2.

**Comment by pandaskii** [comment]
@sonnykt see if discussions in #4 can resolve this issue

```
composer install --prefer-dist --working-dir=build
```

**Comment by fiasco** [comment]
From what I see here: http://apple.stackexchange.com/questions/113379/how-to-debug-trace-bpt-trap-5 it doesn't look like its a govcms related issue but an issue with your working environment. Out testbot and deployment scripts for the SaaS platform are working as expected.

**Comment by sonnykt** [comment]
Look deeper in the build process I reckon it's likely not a govCMS issue but drush/php itself on OSX. Phing executes the below command and terminates because of exit status 1 from Drush.

```
drush --concurrency=8 --no-recursion --no-core --cache-duration-releasexml --contrib-destination=profiles/govcms --nocolor --root=docroot --yes --verbose make "drupal-org.make" "docroot"
```

I ran this command alone and got the same status code 1. Drush reported "Command dispatch complete" but returned exit code 1 because of some `Interrupted system call` warnings.

It's a bit weird that I got no issue with 7.x-2.0-beta9 but same error from 7.x-2.0-beta10.

**Comment by sonnykt** [comment]
UPDATE: 
Debugging drush while building shows me an interesting error: `Unable to clone token_tweaks from https://git.drupal.org/project/token_tweaks.git`. Line 140 in `drupal-org.make`:

```
projects[token_tweaks][download][url] = "https://git.drupal.org/project/token_tweaks.git"
```

Other modules on `git.drupal.org` all use the protocol `http` in `drupal-org.make` (eg. shield, spamspan, etc.) but `token_tweaks`. When I changed the protocol to `http://` or even `git://` the build process completed successfully.

It's a bit confused to me as I could run `git clone https://git.drupal.org/project/token_tweaks.git docroot/profiles/govcms/modules/contrib/token_tweaks` separately without any error. I didn't get this build  failure on Linux either.

**Comment by fiasco** [comment]
Perhaps the client you're using to download over SSL doesn't support the encryption level?

**Comment by sonnykt** [comment]
I'm using:
- OSX 10.11.5
- PHP 5.6.15 (cli) (built: Nov 16 2015 14:38:12) 
- Drush 8.1.2
- GNU Wget 1.17.1 built on darwin15.3.0
- curl 7.47.1 (x86_64-apple-darwin15.3.0) libcurl/7.47.1 OpenSSL/1.0.2g zlib/1.2.8

```
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```
- OpenSSL 1.0.2g  1 Mar 2016

Gave it a try today and it still failed when cloning token_tweaks from `https://git.drupal.org/project/token_tweaks.git`. I can run `git clone` from this project separately, but it failed when cloning it in the context of phing build or even just `drush make`. I doubt if my client does not support the SSL encryption level because it can clone projects on github over SSL (eg. chosen, Superfish, jquery-placeholder, etc.).

Is there any recent changes on Drupal git repository I'm not aware of?

**Comment by fiasco** [comment]
What is the full command that drush is running when it clones from git?

**Comment by sonnykt** [comment]
Didn't have time to debug and capture the whole command, but from what I see in the the log:

```
git clone https://git.drupal.org/project/token_tweaks.git /tmp/drush_tmp_1464741162_574e2d2a65f56/token_tweaks 2>&1
```

**Comment by fiasco** [comment]
Yeah I dunno, seems to work for me

```
git clone https://git.drupal.org/project/token_tweaks.git /tmp/drush_tmp_1464741162_574e2d2a65f56/token_tweaks
Cloning into '/tmp/drush_tmp_1464741162_574e2d2a65f56/token_tweaks'...
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 18 (delta 6), reused 0 (delta 0)
Unpacking objects: 100% (18/18), done.
Checking connectivity... done.
```

**Comment by sonnykt** [comment]
I think we can close the issue. I believe there is an issue with my PHP/cURL/OpenSSL. I can run the `git clone` without any issue but couldn't execute it in the context of PHP with `exec()`.

```
$ php -a
php > exec('git clone --verbose https://git.drupal.org/project/token_tweaks.git /tmp/drush_tmp_1464741162_574e2d2a65f56/token_tweaks');
Cloning into '/tmp/drush_tmp_1464741162_574e2d2a65f56/token_tweaks'...
fatal: unable to access 'https://git.drupal.org/project/token_tweaks.git/': SSL certificate problem: unable to get local issuer certificate
```

I had to disable `httpsVerify` option in git to make it work. Unsure why it happens to git in context of PHP. I don't have the same issue when executing wget/curl in PHP with latest CA file for cURL and OpenSSL.

**Comment by fiasco** [comment]
I think we can close this on off.
