### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by paulkilla** [govCMS/GovCMS7#4]
Hi,

Congrats with the release!

I'm following the instructions on github, but have troubles trying to make a build with the command:

build/bin/phing -f build/phing/build.xml build
Execution of target "make:local" failed for the following reason: /var/www/govcms/build/phing/build.xml:287:38: Drush exited with code 1
[phingcall] /var/www/govcms/build/phing/build.xml:287:38: Drush exited with code 1
       [if] Error in IfTask
Execution of target "make" failed for the following reason: /var/www/govcms/build/phing/build.xml:225:12: Error in IfTask

I've tried it on several Linux machines and the outcome is always this. I would be very helpful to any directions towards solving this.
Cheers!

---

Hey pkil,

Thanks for your reply.
There were no errors while running this command (composer install --prefer-dist --working-dir=build), what I currently get is:
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

> PhantomInstaller\Installer::installPhantomJS
> - Installing phantomjs (1.9.8)
>   Loading from cache

Don't think you can tell anything from this?:)

Btw, I'm running Ubuntu.

---

**Comment by barbun** [comment]
Thanks for your help!
However, still no luck. Now it fails a bit farther though :)

```
Calling install_drupal(Array) [0.17 sec, 7.84 MB]                                                                                                                           [debug]
exception 'Exception' with message 'Resolve all issues below to continue the installation. For help configuring your database server, see the <a                            [error]
href="http://drupal.org/getting-started/install">installation handbook</a>, or contact your hosting provider.<p class="error">Failed to connect to your database server.
The server reports the following message: <em>SQLSTATE[28000] [1045] Access denied for user &#039;root&#039;@&#039;localhost&#039; (using password: NO)</em>.<ul><li>Is
the database server running?</li><li>Does the database exist, and have you entered the correct database name?</li><li>Have you entered the correct username and
password?</li><li>Have you entered the correct database hostname?</li></ul></p>' in /var/www/govcms/docroot/includes/install.core.inc:415
Stack trace:
#0 /var/www/govcms/docroot/includes/install.core.inc(339): install_run_task(Array, Array)
#1 /var/www/govcms/docroot/includes/install.core.inc(77): install_run_tasks(Array)
#2 /var/www/govcms/build/vendor/drush/drush/includes/drush.inc(708): install_drupal(Array)
#3 /var/www/govcms/build/vendor/drush/drush/includes/drush.inc(694): drush_call_user_func_array('install_drupal', Array)
#4 /var/www/govcms/build/vendor/drush/drush/commands/core/drupal/site_install_7.inc(80): drush_op('install_drupal', Array)
#5 /var/www/govcms/build/vendor/drush/drush/commands/core/site_install.drush.inc(289): drush_core_site_install_version('govcms', Array)
#6 [internal function]: drush_core_site_install('govcms')
#7 /var/www/govcms/build/vendor/drush/drush/includes/command.inc(368): call_user_func_array('drush_core_site...', Array)
#8 /var/www/govcms/build/vendor/drush/drush/includes/command.inc(219): _drush_invoke_hooks(Array, Array)
#9 [internal function]: drush_command('govcms')
#10 /var/www/govcms/build/vendor/drush/drush/includes/command.inc(187): call_user_func_array('drush_command', Array)
#11 /var/www/govcms/build/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#12 /var/www/govcms/build/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 /var/www/govcms/build/vendor/drush/drush/drush.php(11): drush_main()
#14 {main} [0.61 sec, 20.56 MB]
Command dispatch complete [0.61 sec, 20.49 MB]                                                                                                                             [notice]
 Timer  Cum (sec)  Count  Avg (msec) 
 page   0.44       1      440.49
    [drush] You are about to create a /var/www/govcms/docroot/sites/default/settings.php file and CREATE the 'travis_ci_govcms_drupal' database. Do you want to continue? (y/n): y
    [drush]   ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Execution of target "install" failed for the following reason: /var/www/govcms/build/phing/build.xml:410:38: Drush exited with code 1

BUILD FAILED
/var/www/govcms/build/phing/build.xml:410:38: Drush exited with code 1
Total time: 9.8648 seconds
```

Then, as a workaround, I tried to set my root password to empty value, and got this:

```
Unable to send e-mail. Contact the site administrator if the problem persists. [77.66 sec, 103.69 MB]                                                                       [error]
Thank you for installing the Metatag module. It is recommended to read the module's README.txt file as there are some known issues that may affect this site. [77.66       [status]
sec, 103.69 MB]
Honeypot installed successfully. Please configure Honeypot to protect your forms from spam bots. [77.66 sec, 103.69 MB]                                                    [status]
To use menu blocks, find the "Add menu block" link on the administer blocks page. [77.66 sec, 103.69 MB]                                                                   [status]
Password policy module successfully installed. Please review the available configuration settings. [77.66 sec, 103.7 MB]                                                   [status]
Risky permissions have been automatically disabled. [77.66 sec, 103.7 MB]                                                                                                  [status]
To use Superfish go to the administer blocks page and enable a Superfish block. [77.66 sec, 103.7 MB]                                                                      [status]
Content permissions have been rebuilt. [77.66 sec, 103.7 MB]                                                                                                               [status]
The sitemap links were rebuilt. [77.66 sec, 103.7 MB]                                                                                                                      [status]
Content permissions have been rebuilt. [77.66 sec, 103.7 MB]                                                                                                               [status]
Command dispatch complete [77.66 sec, 103.65 MB]                                                                                                                           [notice]
 Timer                Cum (sec)  Count  Avg (msec) 
 page                 77.46      1      77459.91   
 drupal_http_request  0.188      90     2.085
    [drush] You are about to create a /var/www/govcms/docroot/sites/default/settings.php file and CREATE the 'travis_ci_govcms_drupal' database. Do you want to continue? (y/n): y
Execution of target "install" failed for the following reason: /var/www/govcms/build/phing/build.xml:410:38: Drush exited with code 1

BUILD FAILED
/var/www/govcms/build/phing/build.xml:410:38: Drush exited with code 1
Total time: 2 minutes  30.63 seconds
```

Also, I was expecting to specify the database and credentials myself, so I went to /build/phing/ and created build.properties based on the default.build.properties file that is already in there. Then when I try to:

`../bin/phing build:no-clean`

I get

```
Buildfile: /var/www/govcms/build/phing/build.xml
     [exec] 
     [exec] master
 [property] Loading /var/www/govcms/build/phing/build.properties

BUILD FAILED
Target 'build:no-clean' does not exist in this project.
Total time: 0.0893 seconds
```

And if I just run the usual build the build.properties file gets erased.

**Comment by seanhamlin** [comment]
It is worth mentioning that you can use a different username and password (and database) if you specify this in the build.properties file. You need to copy the example one https://github.com/govCMS/govCMS/blob/master/build/phing/example.build.properties to a new file in the same directory (with the name of build.properties).

Edit, I see towards the end of you comment you did this. interesting.

**Comment by barbun** [comment]
Thanks @seanhamlin, that's exactly what I did. And after running:
<code>build/bin/phing -f build/phing/build.xml build</code>

The build still fails and the build.properties file is not there anymore. I described this at the bottom of my previous comment.

**Comment by typhonius** [comment]
You'll need to run `build:local` or commit changes to your branch to not run the `git clean` step that cleans the repo

**Comment by barbun** [comment]
Thanks @typhonius , that did work, I was following the installation instructions and it says build:no-clean so maybe you need to adjust that.

However, the build still didn't work for me:

```
WD twitter_block: Locally cached widget code file has been saved. [63.46 sec, 106.06 MB]                                                                                     [info]
sh: 1: /usr/sbin/sendmail: not found
WD mail: Error sending e-mail (from root@[127.0.0.1] to root@[127.0.0.1]). [75.35 sec, 103.99 MB]                                                                           [error]
WD cron: Cron run completed. [75.37 sec, 103.98 MB]                                                                                                                        [notice]
Installation complete.  User name: admin  User password: V7K7NoErbr [75.38 sec, 103.97 MB]                                                                                     [ok]
Returned from hook drush_core_site_install [75.38 sec, 103.96 MB]                                                                                                           [debug]
Unable to send e-mail. Contact the site administrator if the problem persists. [75.38 sec, 103.97 MB]                                                                       [error]
Thank you for installing the Metatag module. It is recommended to read the module's README.txt file as there are some known issues that may affect this site. [75.38       [status]
sec, 103.97 MB]
Honeypot installed successfully. Please configure Honeypot to protect your forms from spam bots. [75.38 sec, 103.97 MB]                                                    [status]
To use menu blocks, find the "Add menu block" link on the administer blocks page. [75.38 sec, 103.97 MB]                                                                   [status]
Password policy module successfully installed. Please review the available configuration settings. [75.38 sec, 103.97 MB]                                                  [status]
Risky permissions have been automatically disabled. [75.38 sec, 103.97 MB]                                                                                                 [status]
To use Superfish go to the administer blocks page and enable a Superfish block. [75.38 sec, 103.97 MB]                                                                     [status]
Content permissions have been rebuilt. [75.38 sec, 103.97 MB]                                                                                                              [status]
The sitemap links were rebuilt. [75.38 sec, 103.97 MB]                                                                                                                     [status]
Content permissions have been rebuilt. [75.38 sec, 103.98 MB]                                                                                                              [status]
Command dispatch complete [75.38 sec, 103.93 MB]                                                                                                                           [notice]
 Timer                Cum (sec)  Count  Avg (msec) 
 page                 74.846     1      74846.4    
 drupal_http_request  0.142      109    1.298
    [drush] You are about to create a /var/www/govcms/docroot/sites/default/settings.php file and DROP all tables in your 'govcms' database. Do you want to continue? (y/n): y
    [drush]   actions
    [drush]   authmap
    [drush]   batch
    [drush]   bean
    [drush]   bean_revision
    [drush]   bean_type
    [drush]   block
    [drush]   block_custom
    [drush]   block_node_type
    [drush]   block_role
    [drush]   blocked_ips
    [drush]   cache
    [drush]   cache_block
    [drush]   cache_bootstrap
    [drush]   cache_entity_comment
    [drush]   cache_entity_file
    [drush]   cache_entity_node
    [drush]   cache_entity_taxonomy_term
    [drush]   cache_entity_taxonomy_vocabulary
    [drush]   cache_entity_user
    [drush]   cache_field
    [drush]   cache_filter
    [drush]   cache_form
    [drush]   cache_image
    [drush]   cache_libraries
    [drush]   cache_menu
    [drush]   cache_metatag
    [drush]   cache_page
    [drush]   cache_panels
    [drush]   cache_path
    [drush]   cache_rules
    [drush]   cache_token
    [drush]   cache_update
    [drush]   cache_views
    [drush]   cache_views_data
    [drush]   ccl
    [drush]   comment
    [drush]   contact
    [drush]   context
    [drush]   ctools_css_cache
    [drush]   ctools_object_cache
    [drush]   date_format_locale
    [drush]   date_format_type
    [drush]   date_formats
    [drush]   defaultconfig_optionals
    [drush]   defaultcontent
    [drush]   draggableviews_structure
    [drush]   ds_field_settings
    [drush]   ds_fields
    [drush]   ds_layout_settings
    [drush]   ds_view_modes
    [drush]   event_log
    [drush]   field_config
    [drush]   field_config_instance
    [drush]   field_data_body
    [drush]   field_data_comment_body
    [drush]   field_data_field_bean_body
    [drush]   field_data_field_bean_image
    [drush]   field_data_field_bean_text
    [drush]   field_data_field_contact
    [drush]   field_data_field_cost
    [drush]   field_data_field_date
    [drush]   field_data_field_description
    [drush]   field_data_field_documents
    [drush]   field_data_field_event_date
    [drush]   field_data_field_feature_image
    [drush]   field_data_field_file
    [drush]   field_data_field_file_image_alt_text
    [drush]   field_data_field_file_image_title_text
    [drush]   field_data_field_image
    [drush]   field_data_field_link_to
    [drush]   field_data_field_location
    [drush]   field_data_field_news_date
    [drush]   field_data_field_read_more
    [drush]   field_data_field_reference
    [drush]   field_data_field_slide_image
    [drush]   field_data_field_subtitle
    [drush]   field_data_field_tags
    [drush]   field_data_field_thumbnail
    [drush]   field_revision_body
    [drush]   field_revision_comment_body
    [drush]   field_revision_field_bean_body
    [drush]   field_revision_field_bean_image
    [drush]   field_revision_field_bean_text
    [drush]   field_revision_field_contact
    [drush]   field_revision_field_cost
    [drush]   field_revision_field_date
    [drush]   field_revision_field_description
    [drush]   field_revision_field_documents
    [drush]   field_revision_field_event_date
    [drush]   field_revision_field_feature_image
    [drush]   field_revision_field_file
    [drush]   field_revision_field_file_image_alt_text
    [drush]   field_revision_field_file_image_title_text
    [drush]   field_revision_field_image
    [drush]   field_revision_field_link_to
    [drush]   field_revision_field_location
    [drush]   field_revision_field_news_date
    [drush]   field_revision_field_read_more
    [drush]   field_revision_field_reference
    [drush]   field_revision_field_slide_image
    [drush]   field_revision_field_subtitle
    [drush]   field_revision_field_tags
    [drush]   field_revision_field_thumbnail
    [drush]   file_display
    [drush]   file_managed
    [drush]   file_metadata
    [drush]   file_type
    [drush]   file_usage
    [drush]   filter
    [drush]   filter_format
    [drush]   flood
    [drush]   history
    [drush]   honeypot_user
    [drush]   image_effects
    [drush]   image_styles
    [drush]   linkchecker_block_custom
    [drush]   linkchecker_comment
    [drush]   linkchecker_link
    [drush]   linkchecker_node
    [drush]   linkit_profiles
    [drush]   login_destination
    [drush]   login_security_track
    [drush]   menu_custom
    [drush]   menu_links
    [drush]   menu_router
    [drush]   metatag
    [drush]   metatag_config
    [drush]   node
    [drush]   node_access
    [drush]   node_comment_statistics
    [drush]   node_revision
    [drush]   node_type
    [drush]   oauth_common_consumer
    [drush]   oauth_common_context
    [drush]   oauth_common_nonce
    [drush]   oauth_common_provider_consumer
    [drush]   oauth_common_provider_token
    [drush]   oauth_common_token
    [drush]   page_manager_handlers
    [drush]   page_manager_pages
    [drush]   page_manager_weights
    [drush]   panels_display
    [drush]   panels_layout
    [drush]   panels_pane
    [drush]   panels_renderer_pipeline
    [drush]   password_policy
    [drush]   password_policy_expiration
    [drush]   password_policy_force_change
    [drush]   password_policy_history
    [drush]   password_policy_role
    [drush]   pathauto_persist
    [drush]   queue
    [drush]   quicktabs
    [drush]   rdf_mapping
    [drush]   redirect
    [drush]   registry
    [drush]   registry_file
    [drush]   role
    [drush]   role_permission
    [drush]   rules_config
    [drush]   rules_dependencies
    [drush]   rules_scheduler
    [drush]   rules_tags
    [drush]   rules_trigger
    [drush]   scheduler
    [drush]   search_api_db_default_node_index
    [drush]   search_api_db_default_node_index_field_tags
    [drush]   search_api_db_default_node_index_text
    [drush]   search_api_index
    [drush]   search_api_item
    [drush]   search_api_page
    [drush]   search_api_server
    [drush]   search_api_task
    [drush]   search_dataset
    [drush]   search_index
    [drush]   search_node_links
    [drush]   search_total
    [drush]   semaphore
    [drush]   sequences
    [drush]   sessions
    [drush]   shortcut_set
    [drush]   shortcut_set_users
    [drush]   system
    [drush]   taxonomy_index
    [drush]   taxonomy_term_data
    [drush]   taxonomy_term_hierarchy
    [drush]   taxonomy_vocabulary
    [drush]   twitter_block
    [drush]   url_alias
    [drush]   userprotect
    [drush]   users
    [drush]   users_roles
    [drush]   variable
    [drush]   views_display
    [drush]   views_view
    [drush]   webform
    [drush]   webform_clear
    [drush]   webform_component
    [drush]   webform_conditional
    [drush]   webform_conditional_rules
    [drush]   webform_emails
    [drush]   webform_last_download
    [drush]   webform_roles
    [drush]   webform_submissions
    [drush]   webform_submitted_data
    [drush]   workbench_moderation_node_history
    [drush]   workbench_moderation_states
    [drush]   workbench_moderation_transitions
    [drush]   wysiwyg
    [drush]   wysiwyg_user
    [drush]   xmlsitemap
    [drush]   xmlsitemap_sitemap
Execution of target "install" failed for the following reason: /var/www/govcms/build/phing/build.xml:410:38: Drush exited with code 1

BUILD FAILED
/var/www/govcms/build/phing/build.xml:410:38: Drush exited with code 1
Total time: 1 minutes  27.12 seconds
```

It did finally succeed after I installed sendmail. Now I'm thinking that it has to be included as dependency?

**Comment by barbun** [comment]
Now the funny part, it did work when my db user pass was empty, once I brought it back and specified it in the build.properties

```
; The uri of the site.
drupal.base_url='http://govcms.local/'

; The database settings.
db.name=govcms
db.username=root
dp.password=root
; db.port=DB_PORT
</code>

The build fails again:

<code>
exception 'Exception' with message 'Resolve all issues below to continue the installation. For help configuring your database server, see the <a                            [error]
href="http://drupal.org/getting-started/install">installation handbook</a>, or contact your hosting provider.<p class="error">Failed to connect to your database server.
The server reports the following message: <em>SQLSTATE[28000] [1045] Access denied for user &#039;root&#039;@&#039;localhost&#039; (using password: NO)</em>.<ul><li>Is
the database server running?</li><li>Does the database exist, and have you entered the correct database name?</li><li>Have you entered the correct username and
password?</li><li>Have you entered the correct database hostname?</li></ul></p>' in /var/www/govcms/docroot/includes/install.core.inc:415
Stack trace:
#0 /var/www/govcms/docroot/includes/install.core.inc(339): install_run_task(Array, Array)
#1 /var/www/govcms/docroot/includes/install.core.inc(77): install_run_tasks(Array)
#2 /var/www/govcms/build/vendor/drush/drush/includes/drush.inc(708): install_drupal(Array)
#3 /var/www/govcms/build/vendor/drush/drush/includes/drush.inc(694): drush_call_user_func_array('install_drupal', Array)
#4 /var/www/govcms/build/vendor/drush/drush/commands/core/drupal/site_install_7.inc(80): drush_op('install_drupal', Array)
#5 /var/www/govcms/build/vendor/drush/drush/commands/core/site_install.drush.inc(289): drush_core_site_install_version('govcms', Array)
#6 [internal function]: drush_core_site_install('govcms')
#7 /var/www/govcms/build/vendor/drush/drush/includes/command.inc(368): call_user_func_array('drush_core_site...', Array)
#8 /var/www/govcms/build/vendor/drush/drush/includes/command.inc(219): _drush_invoke_hooks(Array, Array)
#9 [internal function]: drush_command('govcms')
#10 /var/www/govcms/build/vendor/drush/drush/includes/command.inc(187): call_user_func_array('drush_command', Array)
#11 /var/www/govcms/build/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#12 /var/www/govcms/build/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 /var/www/govcms/build/vendor/drush/drush/drush.php(11): drush_main()
#14 {main} [0.61 sec, 20.63 MB]
Command dispatch complete [0.61 sec, 20.56 MB]                                                                                                                             [notice]
 Timer  Cum (sec)  Count  Avg (msec) 
 page   0.438      1      438.18
    [drush] You are about to create a /var/www/govcms/docroot/sites/default/settings.php file and CREATE the 'govcms' database. Do you want to continue? (y/n): y
    [drush]   ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Execution of target "install" failed for the following reason: /var/www/govcms/build/phing/build.xml:410:38: Drush exited with code 1

BUILD FAILED
/var/www/govcms/build/phing/build.xml:410:38: Drush exited with code 1
Total time: 14.0675 seconds
```

**Comment by typhonius** [comment]
`dp.password=root`

This should be `db.password`

**Comment by barbun** [comment]
@typhonius Damn...sorry, what a stupid oversight :+1: 
The build works now! Thanks!

**Comment by typhonius** [comment]
> It did finally succeed after I installed sendmail. Now I'm thinking that it has to be included as dependency?

Managing the dependencies of a local machine on top of the code base is out of scope for this repo. We get around this when testing in travis by setting up a dummy service. Consider also symlinking `/usr/bin/sendmail` to `/bin/true`

**Comment by typhonius** [comment]
Glad your build works - pull requests are welcome if you'd like to document further! :princess:
